<?xml version="1.0"?>
<definitions name="StockQuote"
  targetNamespace="http://example.com/stockquote/definitions" xmlns:tns="http://example.com/stockquote/definitions"
  xmlns:xsd1="http://example.com/stockquote/schemas" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:msg="http://example.com/stockquote/messages" xmlns="http://schemas.xmlsoap.org/wsdl/">
  
  <import namespace="http://example.com/stockquote/messages"
    location="stockquotemessages.wsdl" />

  <portType name="StockQuotePortType">
    <operation name="GetLastTradePrice">
      <input message="msg:GetLastTradePriceInput" />
      <output message="msg:GetLastTradePriceOutput" />
    </operation>
  </portType>
</definitions>
